# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class TodoEisenhower < Formula
  desc "Visualize todo.txt files as an Eisenhower matrix in your terminal"
  homepage "https://github.com/quii/todo-eisenhower"
  version "0.17.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/quii/todo-eisenhower/releases/download/v0.17.0/todo-eisenhower-0.17.0-darwin-amd64.tar.gz"
      sha256 "e2f04ceeae01abcc5bd675022385116c2ee435263c5cde428328b63f930e8c35"

      def install
        bin.install "eisenhower"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/quii/todo-eisenhower/releases/download/v0.17.0/todo-eisenhower-0.17.0-darwin-arm64.tar.gz"
      sha256 "4b62d7a40f628f12832f821cba30dcd8901a764035db15820e3a9c8a846b1040"

      def install
        bin.install "eisenhower"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/quii/todo-eisenhower/releases/download/v0.17.0/todo-eisenhower-0.17.0-linux-amd64.tar.gz"
      sha256 "5853f0de0473559c95b49af3edba874b6d00a605a4d9ed98c9b9c42ee4117c34"
      def install
        bin.install "eisenhower"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/quii/todo-eisenhower/releases/download/v0.17.0/todo-eisenhower-0.17.0-linux-arm64.tar.gz"
      sha256 "41a602a281772dcb487bd5989561c8c35a14ca63c2b2c85e0a05ac4993d29279"
      def install
        bin.install "eisenhower"
      end
    end
  end
end
