# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class TodoEisenhower < Formula
  desc "Visualize todo.txt files as an Eisenhower matrix in your terminal"
  homepage "https://github.com/quii/todo-eisenhower"
  version "0.11.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/quii/todo-eisenhower/releases/download/v0.11.1/todo-eisenhower-0.11.1-darwin-amd64.tar.gz"
      sha256 "c9c337df3060c59fa439d8e82b64f34056130a0dc46a0e75500ae6ed61433072"

      def install
        bin.install "eisenhower"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/quii/todo-eisenhower/releases/download/v0.11.1/todo-eisenhower-0.11.1-darwin-arm64.tar.gz"
      sha256 "96831120a76a76126a9fe8f2e43ede3198f70a406068a6a4ef787f8969043d1e"

      def install
        bin.install "eisenhower"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/quii/todo-eisenhower/releases/download/v0.11.1/todo-eisenhower-0.11.1-linux-amd64.tar.gz"
      sha256 "0560de7f196a209c8c3d1ba7a6d907b976b549b9d6aa5e7a9bfaa40e551b06da"
      def install
        bin.install "eisenhower"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/quii/todo-eisenhower/releases/download/v0.11.1/todo-eisenhower-0.11.1-linux-arm64.tar.gz"
      sha256 "a72b03a178ded05913eec313801c0dd9b92f507659c53df8af62e476a447ec58"
      def install
        bin.install "eisenhower"
      end
    end
  end
end
